<x-layout :page="$page" :home="true">
<section class="hero" data-slider role="region" aria-roledescription="carousel" aria-label="{{ __('site.sectors') }}" tabindex="0" data-pause="{{ __('site.pause') }}" data-play="{{ __('site.play') }}">
@foreach($slides as $slide)<article class="hero-slide {{ $loop->first?'is-active':'' }}" data-slide aria-hidden="{{ $loop->first?'false':'true' }}" @if(!$loop->first) inert @endif>
<img class="hero-image" @if($loop->first) src="{{ $slide->imageUrl() }}" fetchpriority="high" @else data-src="{{ $slide->imageUrl() }}" @endif width="1672" height="941" alt="{{ $slide->tr('alt') }}">
<div class="hero-shade"></div><div class="container hero-content"><div class="hero-copy"><span class="eyebrow light"><span class="gold-line"></span>{{ __('site.eyebrow') }}</span>@if($loop->first)<h1>{{ $slide->tr('title') }}</h1>@else<h2 class="hero-title">{{ $slide->tr('title') }}</h2>@endif<p>{{ $slide->tr('excerpt') }}</p><a class="button" href="{{ url(app()->getLocale().$slide->link) }}">{{ $slide->tr('button') }} <span>{{ __('site.arrow') }}</span></a></div></div>
</article>@endforeach
<div class="orbit hero-orbit" aria-hidden="true"></div>
<div class="container hero-controls"><div class="slide-label"><span class="slide-current" data-current>01</span><span class="slide-line"></span><span>04</span></div><div class="slide-dots">@foreach($slides as $slide)<button data-dot="{{ $loop->index }}" class="{{ $loop->first?'active':'' }}" aria-label="{{ $slide->tr('title') }}" aria-pressed="{{ $loop->first?'true':'false' }}"></button>@endforeach</div><a class="scroll-cue" href="#introduction">{{ __('site.scroll') }} <span>↓</span></a><div class="slide-buttons"><button class="icon-button" data-prev aria-label="{{ __('site.previous') }}">→</button><button class="icon-button" data-next aria-label="{{ __('site.next') }}">←</button><button class="icon-button pause-button" data-pause-toggle aria-label="{{ __('site.pause') }}"><span data-play-icon>Ⅱ</span></button></div></div>
</section>
<div class="sector-ribbon"><div class="container"><span>{{ __('site.company') }}</span><p>{{ app()->getLocale()==='ar'?'شحن · استثمار · مقاولات · إنتاج':'FREIGHT · INVESTMENT · CONTRACTING · PRODUCTION' }}</p><span class="ribbon-orbit" aria-hidden="true">◎</span></div></div>
<section class="section intro-section container" id="introduction"><div class="intro-copy"><span class="eyebrow">{{ __('site.intro_label') }}</span><h2>{{ __('site.intro_title') }}</h2><p class="lead">{{ $page->tr('body') }}</p><a class="text-link" href="{{ route('page',['slug'=>'about']) }}">{{ __('site.intro_link') }} <span>{{ __('site.arrow') }}</span></a>@if($hasProfile)<a class="button button-navy profile-home-button" href="{{ route('profile') }}"><i data-lucide="book-open"></i>{{ __('site.view_profile') }} <span>{{ __('site.arrow') }}</span></a>@endif<div class="intro-rule"><span>01</span><span>{{ __('site.tagline') }}</span></div></div><figure class="intro-photo"><img src="{{ asset('images/sea.webp') }}" width="800" height="700" loading="lazy" alt="{{ app()->getLocale()==='ar'?'سفينة حاويات في ميناء':'Container ship at a port' }}"><figcaption><span>{{ app()->getLocale()==='ar'?'من حركة التجارة، إلى فرص النمو.':'From trade to new possibilities.' }}</span><span aria-hidden="true">↗</span></figcaption><span class="photo-corner" aria-hidden="true"></span></figure></section>
<section class="section sectors-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">{{ __('site.sector_label') }}</span><h2>{{ __('site.sector_title') }}</h2></div><p>{{ __('site.sector_text') }}</p></div><div class="sector-feature">@if($sectors->isNotEmpty())<a class="feature-image" href="{{ route('sector',['slug'=>$sectors->first()->slug]) }}"><img src="{{ asset('images/air.webp') }}" width="800" height="700" loading="lazy" alt="{{ __('site.sectors') }}"><div><span class="eyebrow light">01 / {{ __('site.sectors') }}</span><h3>{{ $sectors->first()?->tr('title') }}</h3><span class="round-arrow">{{ __('site.arrow') }}</span></div></a>@endif<div class="sector-list">@foreach($sectors->take(5) as $sector)<a href="{{ route('sector',['slug'=>$sector->slug]) }}"><span class="index">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><span><h3>{{ $sector->tr('title') }}</h3><small>{{ $sector->tr('excerpt') }}</small></span><span class="list-arrow">{{ __('site.arrow') }}</span></a>@endforeach<a class="all-sectors-link" href="{{ route('sectors') }}">{{ __('site.all_sectors') }} <span>{{ __('site.arrow') }}</span></a></div></div></div></section>
<section class="section discuss-section container"><div><span class="eyebrow">{{ __('site.discuss_label') }}</span><h2>{{ __('site.discuss_title') }}</h2><p>{{ __('site.discuss_text') }}</p><a class="button button-navy" href="{{ route('quote') }}">{{ __('site.quote') }} <span>{{ __('site.arrow') }}</span></a></div><div class="request-list">@foreach(explode('|',__('site.request_types')) as $type)<a href="{{ route('quote') }}"><i data-lucide="{{ ['plane','building-2','package','sprout'][$loop->index] }}"></i><span>{{ $type }}</span><span>{{ __('site.arrow') }}</span></a>@endforeach</div></section>
@if($projects->isNotEmpty())<section class="section container"><div class="section-heading"><h2>{{ __('site.projects') }}</h2><a class="text-link" href="{{ route('listing',['kind'=>'projects']) }}">{{ __('site.discover') }} {{ __('site.arrow') }}</a></div><div class="stories">@foreach($projects as $item)<x-card :item="$item" kind="projects"/>@endforeach</div></section>@endif
@if($news->isNotEmpty())<section class="section container"><div class="section-heading"><h2>{{ __('site.news') }}</h2><a class="text-link" href="{{ route('listing',['kind'=>'news']) }}">{{ __('site.discover') }} {{ __('site.arrow') }}</a></div><div class="stories">@foreach($news as $item)<x-card :item="$item" kind="news"/>@endforeach</div></section>@endif
<x-cta />
</x-layout>