import {chromium, expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const browser = await chromium.launch();
const context = await browser.newContext({viewport: {width:1440,height:1000}, reducedMotion:'reduce'});
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
    await page.goto('http://127.0.0.1:8000/ar/company-profile');
    await expect(page.locator('[data-magazine]')).toHaveClass(/is-enhanced/);
    await expect(page.locator('[data-page-count]')).toHaveText('01');
    await expect(page.locator('[data-previous]')).toHaveAttribute('aria-disabled','true');
    await page.locator('[data-next]').click();
    await expect(page.locator('[data-page-count]')).toHaveText('02');
    await expect(page.locator('[data-book] [data-page-number]')).toHaveCount(1);
    await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
    await page.screenshot({path:'docs/screenshots/profile-desktop.png',fullPage:true});
    for (const number of Array.from({length:15}, (_, index) => index + 3)) {
        await page.locator('[data-next]').click();
        await expect(page.locator('[data-magazine]')).toHaveAttribute('data-current',String(number));
        await expect(page.locator('[data-book] [data-page-number]')).toHaveCount(1);
        for (const image of await page.locator('[data-book] img').all()) {
            expect(await image.evaluate(element => element.complete && element.naturalWidth > 0)).toBe(true);
        }
    }
    await expect(page.locator('[data-page-count]')).toHaveText('17');
    await expect(page.locator('[data-next]')).toHaveAttribute('aria-disabled','true');
    await page.locator('[data-stage]').focus(); await page.keyboard.press('Home');
    await expect(page.locator('[data-page-count]')).toHaveText('01');
    await page.keyboard.press('ArrowLeft'); await expect(page.locator('[data-page-count]')).toHaveText('02');
    await page.keyboard.press('ArrowLeft'); await expect(page.locator('[data-page-count]')).toHaveText('03');
    await page.locator('[data-book] [data-page-number="3"]').click();
    await expect(page.locator('[data-zoom-dialog]')).toBeVisible();
    await expect(page.locator('[data-zoom-title]')).toContainText('3');
    await page.locator('[data-zoom-in]').click(); await expect(page.locator('[data-zoom-level]')).toHaveText('150%');
    await page.locator('[data-zoom-out]').click(); await expect(page.locator('[data-zoom-level]')).toHaveText('100%');
    await page.keyboard.press('Escape'); await expect(page.locator('[data-zoom-dialog]')).not.toBeVisible();
    await expect(page.locator('[data-book] [data-page-number="3"]')).toBeFocused();
    await page.locator('[data-toggle-thumbnails]').click();
    await expect(page.locator('#profile-thumbnails')).toBeVisible();
    await page.locator('[data-thumbnail="9"]').click(); await expect(page.locator('[data-page-count]')).toHaveText('09');
    await page.locator('[data-toggle-thumbnails]').click();
    await page.locator('#profile-page-number').fill('12'); await page.locator('[data-page-form] button').click();
    await expect(page.locator('[data-page-count]')).toHaveText('12');
    await page.locator('.language').click(); await expect(page).toHaveURL(/\/en\/company-profile\?page=12$/);
    await expect(page.locator('[data-page-count]')).toHaveText('12');
    if(await page.locator('[data-fullscreen]').isVisible()) {
        await page.locator('[data-fullscreen]').click();
        await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true);
        await page.locator('[data-fullscreen]').click();
        await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false);
    }
    for(const width of [360,390,768,1440]) {
        await page.setViewportSize({width,height:900});
        await page.goto('http://127.0.0.1:8000/ar/company-profile');
        await expect(page.locator('[data-magazine]')).toHaveClass(/is-enhanced/);
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
        await page.locator('[data-next]').click();
        await expect(page.locator('[data-page-count]')).toHaveText('02');
    }
    await page.setViewportSize({width:390,height:844}); await page.goto('http://127.0.0.1:8000/ar/company-profile');
    const mobileBook = await page.locator('[data-book]').boundingBox();
    await page.mouse.move(mobileBook.x + mobileBook.width * .85, mobileBook.y + mobileBook.height * .6);
    await page.mouse.down();
    await page.mouse.move(mobileBook.x + mobileBook.width * .2, mobileBook.y + mobileBook.height * .6, {steps:12});
    await page.mouse.up();
    await expect(page.locator('[data-page-count]')).toHaveText('02');
    await page.screenshot({path:'docs/screenshots/profile-mobile.png',fullPage:true});
    const axe = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();
    console.log('Accessibility:', JSON.stringify(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))));
    expect(axe.violations).toEqual([]);
    const nojs = await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});
    await nojs.goto('http://127.0.0.1:8000/ar/company-profile');
    await nojs.locator('[data-next]').click(); await expect(nojs).toHaveURL(/page=2$/);
    await expect(nojs.locator('[data-book] img')).toBeVisible();
    await expect(nojs.locator('#profile-thumbnails a')).toHaveCount(17);
    await nojs.close();
    const animatedContext = await browser.newContext({viewport:{width:1440,height:1000}, reducedMotion:'no-preference'});
    const animated = await animatedContext.newPage();
    animated.on('pageerror', error => errors.push(error.message));
    await animated.goto('http://127.0.0.1:8000/ar/company-profile');
    await expect(animated.locator('[data-magazine]')).toHaveClass(/is-enhanced/);
    await animated.locator('[data-stage-next]').click();
    await expect(animated.locator('.paper-turn')).toHaveCount(1);
    await expect(animated.locator('[data-page-count]')).toHaveText('02');
    await expect(animated.locator('.paper-turn')).toHaveCount(0);
    await animated.locator('[data-book] [data-page-number="2"]').click();
    await expect(animated.locator('[data-zoom-dialog]')).toBeVisible();
    await animated.keyboard.press('Escape');
    await expect(animated.locator('[data-book] [data-page-number="2"]')).toBeFocused();
    await animated.keyboard.press('ArrowLeft');
    await expect(animated.locator('[data-page-count]')).toHaveText('03');
    await expect(animated.locator('[data-stage]')).toBeFocused();
    await animated.keyboard.press('ArrowRight');
    await expect(animated.locator('[data-page-count]')).toHaveText('02');
    const dragPage = async distance => {
        const bounds = await animated.locator('[data-book]').boundingBox();
        const start = distance < 0 ? bounds.x + bounds.width * .9 : bounds.x + bounds.width * .1;
        await animated.mouse.move(start, bounds.y + bounds.height * .6);
        await animated.mouse.down();
        await animated.mouse.move(start + distance, bounds.y + bounds.height * .6, {steps:12});
        await animated.mouse.up();
    };
    await dragPage(-35);
    await expect(animated.locator('.paper-turn')).toHaveCount(0);
    await expect(animated.locator('[data-page-count]')).toHaveText('02');
    await expect(animated.locator('[data-zoom-dialog]')).not.toBeVisible();
    await dragPage(-200);
    await expect(animated.locator('[data-page-count]')).toHaveText('03');
    await dragPage(200);
    await expect(animated.locator('[data-page-count]')).toHaveText('02');
    await animated.locator('[data-next]').click({clickCount:2, delay:80});
    await expect(animated.locator('[data-page-count]')).toHaveText('04');
    await expect(animated.locator('[data-book] [data-page-number]')).toHaveCount(1);
    await expect(animated.locator('.paper-turn')).toHaveCount(0);
    await animated.route('**/profile-page-09.webp', route => route.abort());
    await animated.locator('#profile-page-number').fill('9');
    await animated.locator('[data-page-form] button').click();
    await expect(animated.locator('[data-page-error]')).toBeVisible();
    await expect(animated.locator('[data-page-count]')).toHaveText('04');
    await expect(animated.locator('[data-book]')).toHaveAttribute('aria-busy','false');
    await animated.unroute('**/profile-page-09.webp');
    await animated.locator('[data-page-form] button').click();
    await expect(animated.locator('[data-page-count]')).toHaveText('09');
    await animated.emulateMedia({reducedMotion:'reduce'});
    await animated.locator('[data-next]').click();
    await expect(animated.locator('[data-page-count]')).toHaveText('10');
    await expect(animated.locator('.paper-turn')).toHaveCount(0);
    await animated.locator('#profile-page-number').fill('17');
    await animated.locator('[data-page-form] button').click();
    await expect(animated.locator('[data-page-count]')).toHaveText('17');
    await dragPage(-200);
    await expect(animated.locator('[data-page-count]')).toHaveText('17');
    await expect(animated.locator('[data-zoom-dialog]')).not.toBeVisible();
    const touchContext = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'no-preference'});
    const touchPage = await touchContext.newPage();
    touchPage.on('pageerror', error => errors.push(error.message));
    await touchPage.goto('http://127.0.0.1:8000/ar/company-profile');
    await expect(touchPage.locator('[data-magazine]')).toHaveClass(/is-enhanced/);
    await touchPage.locator('[data-book]').scrollIntoViewIfNeeded();
    const touchBounds = await touchPage.locator('[data-book]').boundingBox();
    const touchSession = await touchContext.newCDPSession(touchPage);
    const touchY = touchBounds.y + touchBounds.height * .55;
    await touchSession.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{x:touchBounds.x+touchBounds.width*.85,y:touchY}]});
    for(let step=1;step<=8;step++) {
        await touchSession.send('Input.dispatchTouchEvent', {type:'touchMove',touchPoints:[{x:touchBounds.x+touchBounds.width*(.85-step*.06),y:touchY}]});
    }
    await expect(touchPage.locator('.paper-turn')).toHaveCount(1);
    await touchPage.screenshot({path:'docs/screenshots/profile-turn-mobile.png'});
    await touchSession.send('Input.dispatchTouchEvent', {type:'touchEnd',touchPoints:[]});
    await expect(touchPage.locator('[data-page-count]')).toHaveText('02');
    await expect(touchPage.locator('[data-zoom-dialog]')).not.toBeVisible();
    expect(await touchPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const scrollBefore = await touchPage.evaluate(() => scrollY);
    const nextBounds = await touchPage.locator('[data-book]').boundingBox();
    const verticalX = nextBounds.x + nextBounds.width * .5;
    const verticalY = Math.min(700, nextBounds.y + nextBounds.height * .6);
    await touchSession.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{x:verticalX,y:verticalY}]});
    for(let step=1;step<=6;step++) await touchSession.send('Input.dispatchTouchEvent', {type:'touchMove',touchPoints:[{x:verticalX,y:verticalY-step*25}]});
    await touchSession.send('Input.dispatchTouchEvent', {type:'touchEnd',touchPoints:[]});
    await expect.poll(() => touchPage.evaluate(() => scrollY)).toBeGreaterThan(scrollBefore);
    await expect(touchPage.locator('[data-page-count]')).toHaveText('02');
    await touchContext.close();
    await animatedContext.close();
    expect(errors).toEqual([]);
    console.log('PASS: 17 individual pages, animated paper turns, drag forward/back, drag cancellation, rapid navigation, image failure/retry, reduced motion, boundaries, keyboard, swipe, zoom, focus, thumbnails, jump, language, fullscreen, 4 viewport widths, no-JS fallback.');
} finally {
    await browser.close();
}
